# .github/recent-activity.config.yml
# Example configuration for recent-activity action
activity:
  - type: issue
    action: opened
    label: bug
  - type: pull_request
    action: closed
    merged: true

