name: Update README

on:
  schedule:
    - cron: "0 * * * *"  # Se ejecuta cada hora
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2.4.1
        with:
          GH_USERNAME: "isaacgm8"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Agregar este parámetro
          CONFIG_FILE: ".github/recent-activity.config.yml"


